"""meal correlation support

Revision ID: 9454057bc162
Revises: a7c3e9f1b2d4

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9454057bc162'
down_revision: Union[str, None] = 'a7c3e9f1b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_details',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('meal_type', sa.String(length=32), nullable=True),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['event_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.add_column('data_point_series', sa.Column('event_record_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'data_point_series_event_record_id_fkey',
        'data_point_series', 'event_record', ['event_record_id'], ['id'], ondelete='SET NULL'
    )
    op.create_index('ix_event_record_meal_source_external_id', 'event_record', ['data_source_id', 'external_id'], unique=True, postgresql_where="category = 'meal'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_record_meal_source_external_id', table_name='event_record', postgresql_where="category = 'meal'")
    op.drop_constraint('data_point_series_event_record_id_fkey', 'data_point_series', type_='foreignkey')
    op.drop_column('data_point_series', 'event_record_id')
    op.drop_table('meal_details')
    # ### end Alembic commands ###
